using System;
using System.IO;
using System.Runtime.InteropServices;
using PhoenixPoint.Modding;
using UnityEngine;

namespace Morgott.Demo.AddUiSounds
{
    /// <summary>
    /// The ADD demo. Everything this file does is a TRIGGER: it loads the bank that ContentTool
    /// baked into this mod's own bundle, and posts one of its events at random when the hotkey is
    /// pressed. It replaces nothing and it decodes nothing. Both clips are short UI blips
    /// (0.35 s and 0.45 s), generated by demos\tools\make_demo_audio.ps1 - a hotkey gag is not a tune,
    /// and a sine under an envelope is ours to publish.
    ///
    /// WHY THIS MOD SHIPS A DLL AND ITS TWIN DOES NOT. Replacing a shipped sound is content: the
    /// media ID already exists and the game already posts an event for it, so a media-only bank in
    /// Dist\Sounds\ is the whole mod (that is ReplaceUiSounds, which has no code at all). ADDING a
    /// sound has no such event - nothing in the game would ever post it - so somebody has to, and
    /// deciding WHEN to post is behaviour. That is the split, and it is why these are two mods.
    /// </summary>
    public class AddUiSoundsMain : ModMain
    {
        /// <summary>The stems in Content\Audio\, which is what the bake names its sounds after.</summary>
        private static readonly string[] Clips =
        {
            "blip_rise", "blip_fall"
        };

        private const string ModId = "morgott.demo.adduisounds";
        private static readonly System.Random Pick = new System.Random();
        private static uint[] events;
        private static GameObject emitter;

        public override void OnModEnabled()
        {
            try { Arm(); }
            catch (Exception ex) { Logger?.LogError("AddUiSounds: " + ex); }
        }

        public override void OnModDisabled()
        {
            if (emitter == null) return;
            AkSoundEngine.UnregisterGameObj(emitter);
            UnityEngine.Object.Destroy(emitter);
            emitter = null;
        }

        private void Arm()
        {
            string dir = Instance?.Entry?.Directory;
            string bundlePath = Path.Combine(dir ?? "", Path.Combine("Dist", "AddUiSounds.bundle"));
            AssetBundle bundle = AssetBundle.LoadFromFile(bundlePath);
            if (bundle == null) { Logger?.LogError("AddUiSounds: no bundle at " + bundlePath); return; }

            string underscored = ModId.Replace('.', '_');
            TextAsset bank = bundle.LoadAsset<TextAsset>(
                "assets/" + ModId + "/audio/banks/" + underscored + ".bnk");
            if (bank == null) { Logger?.LogError("AddUiSounds: the bundle carries no bank"); return; }

            byte[] bytes = bank.bytes;
            GCHandle pin = GCHandle.Alloc(bytes, GCHandleType.Pinned);
            AKRESULT r;
            uint bankId;
            // Copy, never View: for bank version >= 135 View divides by uAlignment, and 0 is a #DE
            // process crash rather than an AKRESULT (ContentTool RECIPES 9).
            try { r = AkSoundEngine.LoadBankMemoryCopy(pin.AddrOfPinnedObject(), (uint)bytes.Length, out bankId); }
            finally { pin.Free(); }
            if (r != AKRESULT.AK_Success) { Logger?.LogError("AddUiSounds: bank load " + r); return; }

            events = new uint[Clips.Length];
            for (int i = 0; i < Clips.Length; i++) events[i] = Hash(underscored + "_" + Clips[i].ToLowerInvariant());

            emitter = new GameObject("AddUiSoundsEmitter");
            UnityEngine.Object.DontDestroyOnLoad(emitter);
            AkSoundEngine.RegisterGameObj(emitter, "AddUiSounds");
            emitter.AddComponent<Hotkey>();
            // The IDs are logged so a run can be correlated with `ct_voices watch`: press Alt+B while
            // it is watching and the posted ID has to be one of these.
            string ids = "";
            for (int i = 0; i < events.Length; i++) ids += (i > 0 ? ", " : "") + Clips[i] + "=" + events[i];
            Logger?.LogInfo("AddUiSounds: bank " + bytes.Length + " B loaded as " + bankId + ", " +
                            events.Length + " clip(s) on Alt+B [" + ids + "]");
        }

        /// <summary>
        /// FNV-1 32-bit, multiply THEN xor, name lowercased UTF-8 - the same function the bake used to
        /// name these events, so the two agree by construction rather than by a table someone keeps
        /// in step by hand. (FNV-1a and the non-lowercased form both score 0 on the shipped set.)
        /// </summary>
        private static uint Hash(string name)
        {
            uint h = 2166136261;
            foreach (byte b in System.Text.Encoding.UTF8.GetBytes(name.ToLowerInvariant()))
            {
                h *= 16777619;
                h ^= b;
            }
            return h;
        }

        /// <summary>
        /// Alt+B, and Alt is the point: the game reads no Alt key anywhere in Assembly-CSharp
        /// (measured - zero hits for KeyCode.LeftAlt/RightAlt), so the chord cannot collide with a
        /// binding. Plain B is used by nothing here either, but the modifier is what makes that safe
        /// to claim without owning the whole binding table.
        /// </summary>
        private sealed class Hotkey : MonoBehaviour
        {
            private void Update()
            {
                if (!Input.GetKeyDown(KeyCode.B)) return;
                if (!Input.GetKey(KeyCode.LeftAlt) && !Input.GetKey(KeyCode.RightAlt)) return;
                if (events == null || events.Length == 0) return;
                AkSoundEngine.PostEvent(events[Pick.Next(events.Length)], gameObject);
            }
        }
    }
}
