// GENERATED by research/wwise/pp_gen/mint_setup.py - do not edit by hand.
// Vorbis setup headers expanded once from ww2ogg 0.24's packed aoTuV_603 codebooks.
// One entry per uHashCodebook; the setup packet is byte-identical inside a group.
using System;

namespace Morgott.ContentTool.Wwise
{
    internal static class WwiseSetupHeaders
    {
        /// <summary>
        /// uHashCodebook -> expanded Vorbis setup header. The mode table is not stored: all four
        /// groups are 1 mode bit with blockflags { false, true }, which WwiseWem.PacketSource bakes
        /// in. See research/wwise/README.md ("Mode table") for the measured values.
        /// </summary>
        internal static readonly System.Collections.Generic.Dictionary<uint, byte[]> ByHash =
            new System.Collections.Generic.Dictionary<uint, byte[]>
            {
                // 2111 files, 1 ch, blocksizes 2^8/2^11, 2 modes (sample: 512955491.wem)
                { 471264238u, Convert.FromBase64String(
                        "BXZvcmJpcylCQ1YBAAgAAAAxTCDFgNCQVQAAEAAAYCQpDpNmSSmllKEoeZiUSEkppZTFMImYlInFGGOMMcYYY4wxxhhjjCA0ZBUA" +
                        "AAQAgCgJjqPmSWrOOWcYJ45yoDlpTjinIAeKUeA5CcL1JmNuprSma27OKSUIDVkFAAACAEBIIYUUUkghhRRiiCGGGGKIIYcccsgh" +
                        "p5xyCiqooIIKMsggg0wy6aSTTjrpqKOOOuootNBCCy200kpMMdVWY669Bl18c84555xzzjnnnHPOCUJDVgEAIAAABEIGGWQQQggh" +
                        "hRRSiCmmmHIKMsiA0JBVAAAgAIAAAAAAR5EUSbEUy7EczdEkT/IsURM10TNFU1RNVVVVVXVdV3Zl13Z113Z9WZiFW7h9WbiFW9iF" +
                        "XfeFYRiGYRiGYRiGYfh93/d93/d9IDRkFQAgAQCgIzmW4ymiIhqi4jmiA4SGrAIAZAAABAAgCZIiKZKjSaZmaq5pm7Zoq7Zty7Is" +
                        "y7IMhIasAgAAAQAEAAAAAACgaZqmaZqmaZqmaZqmaZqmaZqmaZpmWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZl" +
                        "WUBoyCoAQAIAQMdxHMdxJEVSJMdyLAcIDVkFAMgAAAgAQFIsxXI0R3M0x3M8x3M8R3REyZRMzfRMDwgNWQUAAAIACAAAAAAAQDEc" +
                        "xXEcydEkT1It03I1V3M913NN13VdV1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWB0JBVAAAEAAAhnWaWaoAIM5Bh" +
                        "IDRkFQCAAAAAGKEIQwwIDVkFAAAEAACIoeQgmtCa8805DprloKkUm9PBiVSbJ7mpmJtzzjnnnGzOGeOcc84pypnFoJnQmnPOSQya" +
                        "paCZ0JpzznkSmwetqdKac84Z55wOxhlhnHPOadKaB6nZWJtzzlnQmuaouRSbc86JlJsntblUm3POOeecc84555xzzqlenM7BOeGc" +
                        "c86J2ptruQldnHPO+WSc7s0J4ZxzzjnnnHPOOeecc84JQkNWAQBAAAAEYdgYxp2CIH2OBmIUIaYhkx50jw6ToDHIKaQejY5GSqmD" +
                        "UFIZJ6V0gtCQVQAAIAAAhBBSSCGFFFJIIYUUUkghhhhiiCGnnHIKKqikkooqyiizzDLLLLPMMsusw84667DDEEMMMbTSSiw11VZj" +
                        "jbXmnnOuOUhrpbXWWiullFJKKaUgNGQVAAACAEAgZJBBBhmFFFJIIYaYcsopp6CCCggNWQUAAAIACAAAAPAkzxEd0REd0REd0REd" +
                        "0REdz/EcURIlURIl0TItUzM9VVRVV3ZtWZd127eFXdh139d939eNXxeGZVmWZVmWZVmWZVmWZVmWZQlCQ1YBACAAAABCCCGEFFJI" +
                        "IYWUYowxx5yDTkIJgdCQVQAAIACAAAAAAEdxFMeRHMmRJEuyJE3SLM3yNE/zNNETRVE0TVMVXdEVddMWZVM2XdM1ZdNVZdV2Zdm2" +
                        "ZVu3fVm2fd/3fd/3fd/3fd/3fd/XdSA0ZBUAIAEAoCM5kiIpkiI5juNIkgSEhqwCAGQAAAQAoCiO4jiOI0mSJFmSJnmWZ4maqZme" +
                        "6amiCoSGrAIAAAEABAAAAAAAoGiKp5iKp4iK54iOKImWaYmaqrmibMqu67qu67qu67qu67qu67qu67qu67qu67qu67qu67qu67qu" +
                        "67pAaMgqAEACAEBHciRHciRFUiRFciQHCA1ZBQDIAAAIAMAxHENSJMeyLE3zNE/zNNETPdEzPVV0RRcIDVkFAAACAAgAAAAAAMCQ" +
                        "DEuxHM3RJFFSLdVSNdVSLVVUPVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdU0TdM0gdCQlQAAGQAAQz0GGXwQDoMQ" +
                        "S289aAoxB631YEEGpeQchMUQQ4xJDxp00ElKOWiMOeQc5OAxCJljgnGNMUfSEAVCx6BRpqAHQkNWBABRAACAMcYxxBhyzknJoETO" +
                        "MQmdlMg5J6WT0kkpLZYYMyklphJj5Jyj0knJpJQYS4qdpBJjia0AAIAABwCAAAuh0JAVAUAUAABiDFIKKYWUUs4p5pBSyjHlHFJK" +
                        "OaecU845CB2EijEGnYMQKaUcU84p5xyEzEHlnIPQQSgAACDAAQAgwEIoNGRFABAnAOCQHM+TNEsUJUsTRU8UZdcTTVeWNM0UNVFU" +
                        "Vc0TVdVUVdsWTVW2JU0TTUv0VFUTRVUVVdOWTVW1Zc80ZdlUVV0XVdW2ZdsWfle2fd8zTdkWVdXWTdW1ddeWfV22bV2YNM00NVFU" +
                        "VU0UVdV0Vds2VdW2NVF0VVFVZVlUVVlWZdnWVVfWfUsUVddTTdkVVVW2Vdn1bVWWdd90VVtXZVkXVlkWfl33hd/WfaOoqrZuuq6v" +
                        "q7Ls+7JuG7vt+0iaZpqaKKqqJoqqaqqqbZuqa9uWKKqqqKqy7JmqK6uy7OuqK9u+JoqqK6qqLIuqKsuqLPu6Kru6LqqqbquyLPym" +
                        "K+u+7fuM29Z14VRdXVdl2fdVWfZ92/eV4dZ1YfhM07ZNV9V1U3V93dZ145ltXzhGVdV9VZaFYZVl4dd9H933EVVV103ZFXZVloVf" +
                        "F3Zn2X1fKes24dZ9zu77lOGILxy5tq0cs24Tbt1Xlt/4KcszPD3TlG1TVXXddF3dt3Vb+W1dZ4yq6uuqLPNVV/aF2xcqu+8bRVXV" +
                        "fVWWfV+1ZWPYfd94dmHJtW1huH0d2daVvvHk+8bRtW3huX1fafs253eGhDplAADAgAMAQIAJZaDQkBUBQJwAAIOQc4opCJViEDoI" +
                        "KXUQUqoYg5A5JyVjDkooJaUQSmoVYxAyxyRkzkkJJbQUSmmpg5BSKKW1UEprqbUaU2oxdhBSCqW0FkppLbUUW2otxogxCJljUjLm" +
                        "pIRSWgqlpJY5J6VzkFIHIaVSUoulpNYqxqRk0FHpHJRUUomppNRaKKW1UlKMJaUWW2uxthZrDaW0FkqJraQUY2qpthZjrRVjEDLH" +
                        "pGTOSQmltBRKSa1iTEoHHZXMQUklpdZKSSlmzknpIKTUQUeppBJbSSm2UEprJaXYQikttthqTam1GkppraQUY0klttZarS22GjsI" +
                        "KYVSWgultJZaqzG1FmsopbWSUowlpRhbizW3FmsNpbQWUomtlNRii63G1mLNqbUaU2u1thhrjbHWHmvNObUUY2qpxtZiza223GLN" +
                        "uXcQUgqltBZKaS21VmNqLcZQSmslldhCSS222GptLcYaSmmtpBRjSSnGFlutLcZaU0oxtthqTanFWmvtubXacmot1hZjzam1WmOt" +
                        "vccaeywAAGDAAQAgwIQyUGjISgAgCgCAIEQp56Q0CDnmHKUEIeaco1Q5BqGElirmIISSWuechJZi7ByEklqMJaXWYqy1lJRajLUW" +
                        "AABQ4AAAEGCDpsTiAIWGrAQAogAAEGMQYgxCg4xSjEFoDFKKOQiRUow5JyVSijHnpGSOOSchpYw556CUFEIoJaWWQgilpJRaAQAA" +
                        "BQ4AAAE2aEosDlBoyIoAIAoAADAGMYYYQ9AxKZ2UyEEmJZPQOAcpdZQySqXEEmNGqcRWYoygc5RCShmlEmNpMaNUYgyxFAAAduAA" +
                        "AHZgIRQashIAyAMAQIxRijHnnDMIMeWcc84ZhBRzzjnnFGOMOeecc4oxxpxzzjnmnHPOQQghc8455yCE0DnnHIQQQuiccw5CCCF0" +
                        "zjkHIYQQOuecgxBCCAUAABU4AAAE2CiyOcFIUKEhKwGAPAAAwBilnINQSqMUYxBKSalRijEIpaRUOQehlJRaq5yDUEpKrXUQSkmp" +
                        "tRg7CKWk1FqMpZSUYowx11BKSy3GWHNqLcYYc805pRZjrTXnXAAA7oIDANiBjSKbE4wEFRqyEgDIAwBAEFKKMcYYQwoxxphjziGk" +
                        "FGOMMecUY4w55pxzSjHGmHPOOcaYc8455xxjjDnnnHOOMeacc845x5xzzjnnnGPOOeecc84x55xzzjnnBAAAFTgAAATYKLI5wUhQ" +
                        "oSErAYBwAACACOg455xzzjk3DmKttdZaa601clBrrbXWWmutqdZaa6211lprTbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lpr" +
                        "rbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211loA" +
                        "kG+FA4D/g40zrCSdFY4GFxqyEgAIBwAAjGHMQeeggw5Cw5RzEEIIIYQQGqYglBJCKaWklEEnJaVSUkoppcxBKSmVklJKqXVSUmot" +
                        "pdZai62TklJLKaXWWosdhFRSaq212GLrIKSUUmuttRhjKCW11lqLMcYYQykptdZajDHWWEppqbUYY4wxxlJSSq3FGGOMMZaUWout" +
                        "xRhjjLWk1FpsMcYaY40FAHA3OABAJNg4w0rSWeFocKEhKwGAkAAABCHGnHPOOegchBApxZhzzjkHIYQQIqUYc8455yCEEELGmHPO" +
                        "QQghhBBCyBhzzjkIIYQQQgidc85BCCGEEEIIoXPOOQghhBBCCCF0zkEIIYQQQgghhM45CCGEEEIIIYTQQQghhBBCCCGEEjoIIYQQ" +
                        "QgghhBBCCCGEEEIIIYRQSgghhBBCCCGEEEIoIYQQQgghhBJCKCGEEEIIIZQQQgmhhBBCCCGEUkoooZQQQgghhFBKKCWEUgAAwIED" +
                        "AECAEXSSUWURNppw4QEoNGQlAEAGAIBAjTX2FmtklHKQSsslQko5KbGXSinlILQaM6WMUoxqyRhTSjGJuYQOKaSkltA5pZBRlFJL" +
                        "JYQIQWk5xhg7xgAAABAEABiIkJlAoAAKDGQAwAFCghQAUFhg6BguAgJyCRkFBoVjwjnptAEACEJkhkhELAaJCdVAUTEdACwuMOQD" +
                        "QIbGRtrFBXQZ4IIu7joQQhCCEMTiAApIwMEJNzzxhifc4ASdolIHAQAAAACAAAAPAADJBhAREc0cR4fHB0iIyAhJickJSgAAAAAA" +
                        "AAHABwBAkgJEREQzx9Hh8QESIjJCUmJyghIAAAAAAAAAAAAEBAQAAAAAAAIAAAAEBA==" +
                        "") },
                // 638 files, 2 ch, blocksizes 2^8/2^11, 2 modes (sample: 548839902.wem)
                { 103219657u, Convert.FromBase64String(
                        "BXZvcmJpcytCQ1YBAAgAAAAxTCDFgNCQVQAAEAAAYCQpDpNmSSmllKEoeZiUSEkppZTFMImYlInFGGOMMcYYY4wxxhhjjCA0ZBUA" +
                        "AAQAgCgJjqPmSWrOOWcYJ45yoDlpTjinIAeKUeA5CcL1JmNuprSma27OKSUIDVkFAAACAEBIIYUUUkghhRRiiCGGGGKIIYcccsgh" +
                        "p5xyCiqooIIKMsggg0wy6aSTTjrpqKOOOuootNBCCy200kpMMdVWY669Bl18c84555xzzjnnnHPOCUJDVgEAIAAABEIGGWQQQggh" +
                        "hRRSiCmmmHIKMsiA0JBVAAAgAIAAAAAAR5EUSbEUy7EczdEkT/IsURM10TNFU1RNVVVVVXVdV3Zl13Z113Z9WZiFW7h9WbiFW9iF" +
                        "XfeFYRiGYRiGYRiGYfh93/d93/d9IDRkFQAgAQCgIzmW4ymiIhqi4jmiA4SGrAIAZAAABAAgCZIiKZKjSaZmaq5pm7Zoq7Zty7Is" +
                        "y7IMhIasAgAAAQAEAAAAAACgaZqmaZqmaZqmaZqmaZqmaZqmaZpmWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZlWZZl" +
                        "WUBoyCoAQAIAQMdxHMdxJEVSJMdyLAcIDVkFAMgAAAgAQFIsxXI0R3M0x3M8x3M8R3REyZRMzfRMDwgNWQUAAAIACAAAAAAAQDEc" +
                        "xXEcydEkT1It03I1V3M913NN13VdV1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWB0JBVAAAEAAAhnWaWaoAIM5Bh" +
                        "IDRkFQCAAAAAGKEIQwwIDVkFAAAEAACIoeQgmtCa8805DprloKkUm9PBiVSbJ7mpmJtzzjnnnGzOGeOcc84pypnFoJnQmnPOSQya" +
                        "paCZ0JpzznkSmwetqdKac84Z55wOxhlhnHPOadKaB6nZWJtzzlnQmuaouRSbc86JlJsntblUm3POOeecc84555xzzqlenM7BOeGc" +
                        "c86J2ptruQldnHPO+WSc7s0J4ZxzzjnnnHPOOeecc84JQkNWAQBAAAAEYdgYxp2CIH2OBmIUIaYhkx50jw6ToDHIKaQejY5GSqmD" +
                        "UFIZJ6V0gtCQVQAAIAAAhBBSSCGFFFJIIYUUUkghhhhiiCGnnHIKKqikkooqyiizzDLLLLPMMsusw84667DDEEMMMbTSSiw11VZj" +
                        "jbXmnnOuOUhrpbXWWiullFJKKaUgNGQVAAACAEAgZJBBBhmFFFJIIYaYcsopp6CCCggNWQUAAAIACAAAAPAkzxEd0REd0REd0REd" +
                        "0REdz/EcURIlURIl0TItUzM9VVRVV3ZtWZd127eFXdh139d939eNXxeGZVmWZVmWZVmWZVmWZVmWZQlCQ1YBACAAAABCCCGEFFJI" +
                        "IYWUYowxx5yDTkIJgdCQVQAAIACAAAAAAEdxFMeRHMmRJEuyJE3SLM3yNE/zNNETRVE0TVMVXdEVddMWZVM2XdM1ZdNVZdV2Zdm2" +
                        "ZVu3fVm2fd/3fd/3fd/3fd/3fd/XdSA0ZBUAIAEAoCM5kiIpkiI5juNIkgSEhqwCAGQAAAQAoCiO4jiOI0mSJFmSJnmWZ4maqZme" +
                        "6amiCoSGrAIAAAEABAAAAAAAoGiKp5iKp4iK54iOKImWaYmaqrmibMqu67qu67qu67qu67qu67qu67qu67qu67qu67qu67qu67qu" +
                        "67pAaMgqAEACAEBHciRHciRFUiRFciQHCA1ZBQDIAAAIAMAxHENSJMeyLE3zNE/zNNETPdEzPVV0RRcIDVkFAAACAAgAAAAAAMCQ" +
                        "DEuxHM3RJFFSLdVSNdVSLVVUPVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdU0TdM0gdCQlQAAGQAAAinFmoRQkkFO" +
                        "SuxFacYgB60G5SmEGJPYi+mYQshRUCpkDBnkQMnUMYYQ82JjpxRCzIvxpXOMQS/GuFJCKMEIQkNWBABRAAAGSSJJJEnyNKJI9CTN" +
                        "I4o8EYAkejyP50meyPN4HgBJFHkez5NEkefxPAEAAAEOAAABFkKhISsCgDgBAIskeR5J8jyS5Hk0TRQhipKmiSLPM02eZopMU1Wh" +
                        "qpKmiSLPM02aJ5pMU1Whqp4oqipVdV2q6bpk27Zhy54oqipVdV2m6rps2bYh2wAAACRPU02aZpo0zTSJompCVSXNM1WaZpo0zTSJ" +
                        "oqlCVT1TdF2m6bpM03W5rixDlj3RdF2mqbpM03W5rixDlgEAAEiep6o0zTRpmmkSRVOFakqep6o0zTRpmmkSRVWFqXqm6bpM03WZ" +
                        "putyZVmGLXum6bpM03WZpuuSXVmGLAMAANBM05aJouwSRddlmq4L19VMU7aJoisTRddlmq4L1xVV1Zappi1TVVnmurIMWRZVVbaZ" +
                        "qmxTVVnmurIMWQYAAAAAAAAAAICoqrZNVWWZasoy15VlyLKoqrZNVWWZqcoy17VlyLIAAIABBwCAABPKQKEhKwGAKAAAh+JYlqaJ" +
                        "IsexLE0TTY5jWZpmiiRJ0zzPNKFZnmea0DRRVFVomiiqKgAAAgAAChwAAAJs0JRYHKDQkJUAQEgAgMNxLEvTPM/zRFE0TZPjWJbn" +
                        "iaIomqZpqirHsSzPE0VRNE3TVFWWpWmeJ4qiaJqqqqrQNM8TRVE0TVVVVWiaKJqmaaqqqrouNE0UTdM0VVVVXRea5nmiaJqq6rqu" +
                        "CzxPFE1TVV3XdQEAAAAAAAAAAAAAAAAAAAAABAAAHDgAAAQYQScZVRZhowkXHoBCQ1YEAFEAAIAxiDHFmFEKQiklNEpBCSWUCkJp" +
                        "qaSUSUittdYyKam11lolpbSWWsugpNZaa5mE1lprrQAAsAMHALADC6HQkJUAQB4AAIKMUow55xw1RinGnHOOGqMUY845R5VSyjnn" +
                        "IKSUKsWccw5SShlzzjnnKKWMOeecc5RS55xzzjlKqZTOOeccpVRK55xzjlIqJWPOOScAAKjAAQAgwEaRzQlGggoNWQkApAIAGBzH" +
                        "sjzP80zRNC1J0jRRFEXTVFVLkjRNFE1RNVWVZWmaKJqmqrouTdM0UTRNVXVdqup5pqmqruu6VFf0TFNVXVeWAQAAAAAAAAAAAAEA" +
                        "4AkOAEAFNqyOcFI0FlhoyEoAIAMAADEGIWQMQsgYhBRCCCmlEBIAADDgAAAQYEIZKDRkJQCQCgAAGKOUc85JSaVCiDHnIJTSUoUQ" +
                        "Y85BKKWlqDHGIJSSUmtRY4xBKCWl1qJrIZSSUkqtRddCKCWl1lqLUqpUSmqtxRilVKmU1lqLMUqpc0qtxRhjlFL3lFqLsdYopXQy" +
                        "xhhjrc0552SMMcZaCwBAaHAAADuwYXWEk6KxwEJDVgIAeQAACEJKMcYYYxAhpRhjzDGHkFKMMcYYVIoxxhxjDkLIGGOMMQchZIwx" +
                        "55yDEDLGGGPOQQidc44x5yCE0DnHmHMQQuecY8w5CKFzjDHmnAAAoAIHAIAAG0U2JxgJKjRkJQAQDgAAGMOYc4w5Bp2ECiHnIHQO" +
                        "QiqpVAg5B6FzEEpJqXgOOikhlFJKKsVzEEoJoZSUWisuhlJKKKWk1FKRMYRSSiklpdaKMaaEkFJKqbVWjDGhhFRSSim2YoyNpaTU" +
                        "WmutFWNsLCWV1lprrRhjjGsptRZjrMUYY1xLqaUYayzGGON7ai3GWGMxxhifW2opplwLADB5cACASrBxhpWks8LR4EJDVgIAuQEA" +
                        "CEJKMcaYY84555xzzkmlGHPOOecghBBCCCGUSjHmnHPOQQchhBBCKBlzzjkHIYQQQgghhFBS6phzDkIIIYQQQgghpdQ55yCEEEII" +
                        "IYQQQkqpc85BCCGEEEIIIYSUUgghhBBCCCGEEEIIKaWUQgghhBBCCCGUElJKKYUQQgglhBJKCCWklFIKIYQQQimlhFJCSSmlFEII" +
                        "pZRQSimhlJBSSimlEEIopZRQSiklpZRSSiWUUkopJZRQSkoppZRKKKGUUEoppZSUUkoplVJKKSWUUkoJKaWUUkqplFJKKaWUUlJK" +
                        "KaWUUimllFJKKaWklFJKKaVSSimllBJKSSmllFJKpZRQSimllFJSSimllEoKpZRSSimlAACgAwcAgAAjKi3ETjOuPAJHFDJMQIWG" +
                        "rAQAUgEAAEIopZRSSik1jFFKKaWUUoocpJRSSimllFJKKaWUUkoplVJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWU" +
                        "UkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSgHA3RcOgD4TNqyOcFI0FlhoyEoAIBUAADCGMcaYcs45pZRzzjkG" +
                        "nZRIKecgdE5KKT2EEEIInYSUegchhBBCKSn1GEMoIZSUUuuxhk46CKW01GsPIYSUWmqp9x4yqCilklLvPbVQUmopxt57SyWz0lpr" +
                        "vefeSyopxtp67zm3klJMLRYAYBLhAIC4YMPqCCdFY4GFhqwCAGIAAAhDDEJIKaWUUkopxhhjjDHGGGOMMcYYY4wxxhhjjDEBAIAJ" +
                        "DgAAAVawK7O0aqO4qZO86IPAJ3TEZmTIpVTM5ETQIzXUYiXYoRXc4AVgoSErAQAyAADEUaw1xl4rYhiEkmosDUGMQYm5ZcYo5STm" +
                        "1imllJNYU8iUUsxZiiV0TClGKaYSQsaUpBhjjCl00lrOPbdUSgsAAIAgAMBAhMwEAgVQYCADAA4QEqQAgMICQ8dwERCQS8goMCgc" +
                        "E85Jpw0AQBAiM0QiYjFITKgGiorpAGBxgSEfADI0NtIuLqDLABd0cdeBEIIQhCAWB1BAAg5OuOGJNzzhBifoFJU6EAAAAAAACAB4" +
                        "AABINoCIaGbmODo8PkBCREZISkxOUFJUBAAAAAAAEAA+AACSFSAimpk5jg6PD5AQkRGSEpMTlBSVAABAAAEAAAAAEEAAAgICAAAA" +
                        "AAABAAAAAgI=" +
                        "") },
                // 196 files, 1 ch, blocksizes 2^9/2^10, 2 modes (sample: 456206984.wem)
                { 3312772280u, Convert.FromBase64String(
                        "BXZvcmJpcyRCQ1YBAEAAABhCECoFrWOOOsgVIYwZoqBCyinHHULQIaMkQ4g6xjXHGGNHuWSKQsmB0JBVAABAAACkHFdQckkt55xz" +
                        "oxhXzHHoIOecc+UgZ8xxCSXnnHOOOeeSco4x55xzoxhXDnIpLeecc4EUR4pxpxjnnHOkHEeKcagY55xzbTG3knLOOeecc+Ygh1Jy" +
                        "rjXnnHOkGGcOcgsl55xzxiBnzHHrIOecc4w1t9RyzjnnnHPOOeecc84555xzjDHnnHPOOeecc24x5xZzrjnnnHPOOeccc84555xz" +
                        "IDRkFQCQAACgoSiK4igOEBqyCgDIAAAQQHEUR5EUS7Ecy9EkDQgNWQUAAAEACAAAoEiGpEiKpViOZmmeJnqiKJqiKquyacqyLMuy" +
                        "67ouEBqyCgBIAABQURTFcBQHCA1ZBQBkAAAIYCiKoziO5FiSpVmeB4SGrAIAgAAABAAAUAxHsRRN8STP8jzP8zzP8zzP8zzP8zzP" +
                        "8zzP8zwNCA1ZBQAgAAAAgihkGANCQ1YBAEAAAAghGhlDnVISXAoWQhwRQx1CzkOppYPgKYUlY9JTrEEIIXzvPffee++B0JBVAAAQ" +
                        "AABhFDiIgcckCCGEYhQnRHGmIAghhOUkWMp56CQI3YMQQrice8u59957IDRkFQAACADAIIQQQgghhBBCCCmklFJIKaaYYoopxxxz" +
                        "zDHHIIMMMuigk046yaSSTjrKJKOOUmsptRRTTLHlFmOttdacc69BKWOMMcYYY4wxxhhjjDHGGCMIDVkFAIAAABAGGWSQQQghhBRS" +
                        "SCmmmHLMMcccA0JDVgEAgAAAAgAAABxFUiRHciRHkiTJkixJkzzLszzLszxN1ERNFVXVVW3X9m1f9m3f1WXf9mXb1WVdlmXdtW1d" +
                        "1l1d13Vd13Vd13Vd13Vd13Vd14HQkFUAgAQAgI7kOI7kOI7kSI6kSAoQGrIKAJABABAAgKM4iuNIjuRYjiVZkiZplmd5lqd5mqiJ" +
                        "HhAasgoAAAQAEAAAAAAAgKIoiqM4jiRZlqZpnqd6oiiaqqqKpqmqqmqapmmapmmapmmapmmapmmapmmapmmapmmapmmapmmapmkC" +
                        "oSGrAAAJAAAdx3EcR3Ecx3EkR5IkIDRkFQAgAwAgAABDURxFcizHkjRLszzL00TP9FxRNnVTV20gNGQVAAAIACAAAAAAAADHczzH" +
                        "czzJkzzLczzHkzxJ0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRNA0JDVgIAZAAAHMWYe1JKqc5BSDEn" +
                        "ZzvGHLSYmw4VQkxaLTZkiBgmrcfSKUKQo5pKyJAximoppVMIKamllNAxxqSm1loqpbQeCA1ZEQBEAQAACCHGEGOIMQYhgxAxxiB0" +
                        "ECLGHIQMQgYhlBRKySCEEkJJkWMMQgchgxBSCaFkEEIpIZUCAAACHAAAAiyEQkNWBABxAgAIQs4hxiBEjEEIJaQUQkgpYgxC5pyU" +
                        "zDkppZTWQimpRYxByJyTkjknJZTSUimltVBKa6WU1kIprbXWak2txRpKaS2U0loppbXUWo2ttRojxiBkzknJnJNSSmmtlNJa5hyV" +
                        "DkJKHYSUSkotlpRazJyT0kFHpYOQUkkltpJSjCWV2EpKMZaUYmwtxtpirDWU0lpJJbaSUowtthpbjDVHjEHJnJOSOSellNJaKam1" +
                        "zDkpHYSUOgcllZRiLCW1mDknpYOQUgchpZJSbCWl2EIprZWUYiwltdhizLW12GooqcWSUowlpRhbjLW22GrspLQWUoktlNJii7HW" +
                        "1lqtoZQYS0oxlpRijDHW3GKsOZTSYkklxpJSiy22XFuMNafWcm0t1txizDXGXHuttefUWq2ptVpbjDXHGnOstebeQWktlBJbKKnF" +
                        "1lqtLcZaQymxlZRiLCXF2GLMtbVYcyglxpJSjCWlGFuMtcYYc06t1dhizDW1VmuttecYa+yptVpbjDW32GqttfZec+y1AACAAQcA" +
                        "gAATykChISsBgCgAAMIYpRiD0CCklGMQGoSUYg5CpRRjzkmplGLMOSmZY85BSCVjzjkIJYUQSkklpRBCKSWlVAAAQIEDAECADZoS" +
                        "iwMUGrISAAgJACAQUoox5yCUklJKEUJMOQYhhFJSai1CSCnmHIRQSkqtVUwx5hyEEEpJqbVKMcacgxBCKSm1ljnnHIQQSkkppdYy" +
                        "5pyDEEIpKaXUWgchhBBKKSWl1lrrIIQQQimlpNRaayGEEEoppaSUWosxhBBCKaWkklJrMZZSSkkppZRSay3GUkopKaWUUkutxZhS" +
                        "Siml1lprLcYYU0oppdRaa7HFGGNqrbXWWosxxhhrTa211lqLMcYYY60FAAAcOAAABBhBJxlVFmGjCRcegEJDVgQAUQAAgDGIMcQY" +
                        "co5ByKBEzjEJmYTIOUelk5JJCaGV1jIpoZWSWuSck9JRyqiUlkJpmaTSWmihAACwAwcAsAMLodCQlQBAHgAAgZBSjDnnHFKKMcac" +
                        "cw4ppRhjzjmnGGPMOeecU4wx5pxzzjHGnHPOOecYY84555xzzjnnnHMOQuecc845B6FzzjnnIITQOeeccxBCKAAAqMABACDARpHN" +
                        "CUaCCg1ZCQCkAgAAyDDmnHNSUmqUYgxCCKWk1CjFGIQQSkkpcw5CCKWk1FrGGHQSSkmptQ5CKKWk1FqMHYQSSkmptRg7CKWklFJr" +
                        "MXYQSkmppdZiLKWk1FprMdZaSkmptdZirDWl1FqMMdZaa0qptRhjrLXWAgDAExwAgApsWB3hpGgssNCQlQBABgDAEADAAQAAAw4A" +
                        "AAEmlIFCQ1YCAKkAAIAxjDnnHIRSGqWcgxBCKak0SjkHIYRSUsqck1BKKSm1ljknpZRSUmqtg1BKSim1FmMHoZSUUmotxg5CKim1" +
                        "FmONHYRSUmotxhhDKSm1FmOMtYZSUmotxhhrLSm1FmONteZaUmotxhprzbUAAIQGBwCwAxtWRzgpGgssNGQlAJAHAEAgxBhjjDmH" +
                        "lGKMMeecQ0oxxphzzjHGGHPOOecYY4w555xzjDHnnHPOOcaYc8455xxzzjnnnHOOOeecc84555xzzjnnnHPOOeecc84JAAAqcAAA" +
                        "CLBRZHOCkaBCQ1YCAOEAAIAxjDnHGHQSUmqYgg5CCCWk0EKjmHMQQiilpNQy6KSkVEpKrcWWOSelpFJSSq3FDkJKKaXUWowxdhBS" +
                        "Siml1mKMtYNQSkotxVhjrR2EUlJqrbUYaw2lpNRabDHWmnMoJaXWWoyx1ppLSq3FWGOtueZcUmottlhrrTXn1FqMMdaaa869p9Zi" +
                        "jLHWmnPuvQAAkwcHAKgEG2dYSTorHA0uNGQlAJAbAIAgxJhzzkEIIYQQQgghUoox5yCEEEIIIZRSSqQUY85BCCGEEEIIIYSMMeeg" +
                        "gxBCCKWUUkopGWPOQQghhBBKKKWEEjrnoIMQQgmllFJKKaV0zjkIIYQQSimllFJK6SCEEEIIpZRSSimllNJBCCGEUEoppZRSSikl" +
                        "hBBCCKWUUkoppZRSSgghhBBKKaWUUkoppZQQQgillFJKKaWUUkopIYQQSimllFJKKaWUUkIIpZRSSimllFJKKaWEEEoppZRSSiml" +
                        "lFJKCaGUUkoppZRSSimllBJKKaWUUkoppZRSSikllFJKKaWUUkoppZRSSiillFJKKaWUUkoppZRQSimllFJKKaWUUkopoZRSSiml" +
                        "lFJKKaWUUgoAADpwAAAIMKLSQuw048ojcEQhwwRUaMhKACAcAABABDoIIYQQQggRcxBCCCGEEEKImIMQQgghhBBCCCGEEEIIpZRS" +
                        "SimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRS" +
                        "SimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppRQAdZnhABg9YeMMK0lnhaPBhYasBADSAgAAYxhjjCnIpLMWY60NYxBCB52EFGqo" +
                        "JaaGMQghdFBKSi22WHMGoaRSSkktxliDzT2DUEoppaQWY605F+NBSCWl1GKrteccjO4glJJSSjHWmnPuvWjQSUmptVpz7j0HXzwI" +
                        "paTWWow9Bx+MMKKUlmKssdYcfBFGGFFKSy3GmnvNvRhjhEopxlp7zrnnXIwRPqUWY6659x58LsL44mLMOffigw8+CGGMkDHm2HPw" +
                        "vRdjjA/CyFxzLsIY44swwvggbK25B1+MEUYYY3zvNfigezHCCCOMMcII3XPRRfhijDFGGF+EAQC5EQ4AiAtGElJnGVYaceMJGCKQ" +
                        "QkNWAQAxAAAEMcYgpJBSSinFGGOMMcYYY4wxxhhjjDHGnGPOOeecAADABAcAgAAr2JVZWrVR3NRJXvRB4BM6YjMy5FIqZnIi6JEa" +
                        "arES7NAKbvACsNCQlQAAGQAA5KSUlFotGkLKQWk1iMgg5STFJCJjkILSgqeQMYhJyh1jCiEFqXbQMYUUoxpSCplSCmqqOYaOMagx" +
                        "J+FSCaUGAABAEAAgICQAwABBwQwAMDhAGDkQ6AggcGgDAAxEyExgUAgNDjIB4AEiQioASExQlC50QQgRpIsgiwcunLjxxA0ndGiD" +
                        "AAAAAACAAIAPAICEAoiIZmauwuICI0Njg6PD4wMkRGQkAAAAAABAAOADACAhASKimZmrsLjAyNDY4Ojw+AAJERkJAAAAAAAAAAAA" +
                        "AgICAAAAAAABAAAAAgI=" +
                        "") },
                // 152 files, 2 ch, blocksizes 2^9/2^10, 2 modes (sample: 522132355.wem)
                { 2141838623u, Convert.FromBase64String(
                        "BXZvcmJpcyRCQ1YBAEAAABhCECoFrWOOOsgVIYwZoqBCyinHHULQIaMkQ4g6xjXHGGNHuWSKQsmB0JBVAABAAACkHFdQckkt55xz" +
                        "oxhXzHHoIOecc+UgZ8xxCSXnnHOOOeeSco4x55xzoxhXDnIpLeecc4EUR4pxpxjnnHOkHEeKcagY55xzbTG3knLOOeecc+Ygh1Jy" +
                        "rjXnnHOkGGcOcgsl55xzxiBnzHHrIOecc4w1t9RyzjnnnHPOOeecc84555xzjDHnnHPOOeecc24x5xZzrjnnnHPOOeccc84555xz" +
                        "IDRkFQCQAACgoSiK4igOEBqyCgDIAAAQQHEUR5EUS7Ecy9EkDQgNWQUAAAEACAAAoEiGpEiKpViOZmmeJnqiKJqiKquyacqyLMuy" +
                        "67ouEBqyCgBIAABQURTFcBQHCA1ZBQBkAAAIYCiKoziO5FiSpVmeB4SGrAIAgAAABAAAUAxHsRRN8STP8jzP8zzP8zzP8zzP8zzP" +
                        "8zzP8zwNCA1ZBQAgAAAAgihkGANCQ1YBAEAAAAghGhlDnVISXAoWQhwRQx1CzkOppYPgKYUlY9JTrEEIIXzvPffee++B0JBVAAAQ" +
                        "AABhFDiIgcckCCGEYhQnRHGmIAghhOUkWMp56CQI3YMQQrice8u59957IDRkFQAACADAIIQQQgghhBBCCCmklFJIKaaYYoopxxxz" +
                        "zDHHIIMMMuigk046yaSSTjrKJKOOUmsptRRTTLHlFmOttdacc69BKWOMMcYYY4wxxhhjjDHGGCMIDVkFAIAAABAGGWSQQQghhBRS" +
                        "SCmmmHLMMcccA0JDVgEAgAAAAgAAABxFUiRHciRHkiTJkixJkzzLszzLszxN1ERNFVXVVW3X9m1f9m3f1WXf9mXb1WVdlmXdtW1d" +
                        "1l1d13Vd13Vd13Vd13Vd13Vd14HQkFUAgAQAgI7kOI7kOI7kSI6kSAoQGrIKAJABABAAgKM4iuNIjuRYjiVZkiZplmd5lqd5mqiJ" +
                        "HhAasgoAAAQAEAAAAAAAgKIoiqM4jiRZlqZpnqd6oiiaqqqKpqmqqmqapmmapmmapmmapmmapmmapmmapmmapmmapmmapmmapmkC" +
                        "oSGrAAAJAAAdx3EcR3Ecx3EkR5IkIDRkFQAgAwAgAABDURxFcizHkjRLszzL00TP9FxRNnVTV20gNGQVAAAIACAAAAAAAADHczzH" +
                        "czzJkzzLczzHkzxJ0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRN0zRNA0JDVgIAZAAAmLTUYu5Fl845KC3W" +
                        "YDLGmJOWi8kYQspJzCVTyBgFLaeMIUMMo9hCx5AxSGJKKWQIIWixxVY6xyDWWmtMqZQYCA1ZEQBEAQAYFAVwJAlwJAkAAAAAAAAA" +
                        "BAAABDgAAARYCIWGrAgA4gQAHI6jafA8eB48D57nOI6nwfPgeRBFiKLjOJoHz4PnQRQhiprnmSJcFaoLW4Zta54nmlBdqCpsG7YN" +
                        "AAAAAAAAAAAAz/NUFa4K14XsQpY9z1NVqCpcF7IMWQYAAAAAAAAAAIAneq4K14WrQpYhy57nqS5UF6oL2YYsAwAAAAAAAAAAwBNF" +
                        "24YsQ5Yhu5BlTxRtG7IMWYYrQ5YBAAAAAAAAAADgiaJtQ5Yhy5BlyK4nirYNWYYsQ5bhugIAAAYcAAACTCgDhYasBACiAAAMiiJJ" +
                        "muZ5sCzPE0VYlueJIjTNE00TmiaKpgnPE0VVhaaJoqoCACAAAKDAAQAgwAZNicUBCg1ZCQCEBAA4FEWSLMuyNM3zPE8UYVma5nme" +
                        "J4qmqZqwLE3zPM8TRdM0TViW54miKJqmqqoqNMvzRFEUTVNVVRWa5nmiaJqqqqquC03zPFE0TVVVVdeF5nmeKJqmqrquLAPPE0XT" +
                        "VFXXlWUAAAAAAAAAAAAAAAAAAAAAAAEAAAcOAAABRtBJRpVF2GjChQeg0JAVAUAUAABgDGJMMWaUklRKSY1SUlJJJZISWiqtZVJa" +
                        "ay3GjEpqrcVYUSmtpdYyKi3G1lomqcXYWisAAOzAAQDswEIoNGQlAJAHAEAQopRSjDFGpVSKMeeck1IqxZhzzlFKGXPOOQgppYo5" +
                        "5xyElFLGnHPOOUopY845ByGl1DnnnHOOUkqpc845Zyml1DnnnLOUUsqYc84JAAAqcAAACLBRZHOCkaBCQ1YCAKkAAAbHsSxP8zxR" +
                        "NE1JkjRNFEVRVV3XkiRNE0VTVFXXpWmaJoqmqaquS9M0TRRNU1Vdl6p6nmmqquvKMtcVRdNUVdeVZQAAAAAAAAAAAEAAAHiCAwBQ" +
                        "gQ2rI5wUjQUWGrISAMgAACAIQUgphZBSCiGlFEJKKYQEAAAMOAAABJhQBgoNWQkApAIAAMYw5pxzEkqJEGIMQimptFQhxBiEUlJq" +
                        "rWmMMQilpNRa0xhjEFJpqbWmUuekpNRajM21zkFIqbUYm5OmlJJSazFGKU0pJaXWYoxS2ppSazHGGqX0OaWWYqw1SimljK3FWGuU" +
                        "UkoZW4ux1gIAEBocAMAObFgd4aRoLLDQkJUAQB4AAGGMUowxxhiEUDHGGHMOQqgUY4w5ByFkjDHnnIMQMsaYc85BCBljzDnnIISM" +
                        "McaYcxBCxpxjzDkIIYTOMeYchBBC5xhzDkIIIWOMOScAAKjAAQAgwEaRzQlGggoNWQkAhAMAAMYoxRhjzkEopVLKOQidg1BKShVC" +
                        "jkHoHIRSUmqecw5CCKWk0lLznHMQQiglpdaaayGUUkpKrcXWZAyhlFJSai3G5pwIIZSSUmuxNedECJ2UllqLsTknYykptRZjjM05" +
                        "GUtJpaUYa23OOadSSq3FWGtzzjlVUoopxlqbk1LamlqMMdYapZRS55ZiqzHXAgBMHhwAoBJsnGEl6axwNLjQkJUAQG4AAGGMUow5" +
                        "55xzzjnnnHOUUsaccw5CCCGEEEIIJZWMOecchBBCCCGEEFJKnXMOQgghhBBCCCGklDrnHIQQQgihhFJKSSl1DkIIIYRQSimllJJS" +
                        "6hyEEEIIpZRSSiklpRRCCCGEUEoppZRSSkoppRBCCKGUUkoppZSUUkohhFBKKaWUUkopKaWUQgihlFJKKaWUUlJKKZVQSimllFJK" +
                        "KaWklFJKqZRSSimllFJKSSmllFIppZRSSimllJJSSimlUkoppZRSSiklpZRSSqWUUkoppZRSSkoppZRSKqWUUkoppZSUUkoppVRK" +
                        "KaWUUkopKaWUUkqplFJKKaWUUlJKKaWUUimllFJKKaWklFJKKaWUSimllFJKKQAA6MABACDAiEoLsdOMK4/AEYUME1ChISsBgJAA" +
                        "AMAQ6aSUUkoppZRSSSmllFJKKaWUUioJpZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml" +
                        "lFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml" +
                        "lFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFIAYHSGA2D0hBF0klFlETaacOEBKDRkJQCQFgAAGMMYY4w5JyGVmGqslHLO" +
                        "OcegoxBTbTVGSjnnnHMQUoqpxpyD55yDEDoKrcRUW43Bc85BCKGUlGKMtefgWucglJJSS7HFVmNvrXMQSkmptRhrzTkIIUIIKbXW" +
                        "Yoy91hqEEB10VFqLsdacew9CuFZKai3GGnOuPQchXCudhdhqzTX33oMQQqjUWq215557DkIIIVRoJaZcew++5yCEEDq3VmvuPfce" +
                        "hBBCCFtbqSm34HMPPgghhBAy1lp7ED4IIYQQQggZYsux9yCEEEIIIYQOtubegw8+CCGEEEIIG3PvwQchDADIjXAAQFwwkpA6y7DS" +
                        "iBtPwBCBFBqyCgCIAQAYAoAgEDAAADDBAQAgwAp2ZZZWbRQ3dZIXfRD4hI7YjAy5lIqZnAh6pIZarAQ7tIIbvAAsNGQlAEAGAMAw" +
                        "CKGDEntkkGLMQesVQogxKC1nChmkHJTYMYYQYlBaxphCSDFpnXOMIaQgdRA6pxRyVFJrKYQOWqw519ZSigEAABAEAAgICQAwQFAw" +
                        "AwAMDhBGDgQ6Aggc2gAAAxEyExgUQoODTAB4gIiQCgASExSlC10QQgTpIsjigQsnbjxxwwkd2kAAAAAAAEAA4AMAIKEAIqKZmauw" +
                        "uMDI0Njg6PD4AAkRGREAAAAAACAA+AAASEiAiGhm5iosLjAyNDY4Ojw+QEJERgIAAAEEAAAAAEAAAQgICAAAAAAABAAAAAgI" +
                        "") },
            };
    }
}
